### ISSUE TITLE
UpperCase

### ISSUE THREAD

**Issue by nreeG** [eirlis/web3j-example#1]
Is it necessary to generate an address with uppercase letters? If yes, why this program is only giving numbers and lowercase letters? Is there any solution? I'm sorry, I am a newbie. I think it was something about checksum.

**Comment by eirlis** [comment]
Hi @nreeG! In case of Ethereum addresses, capitalization is just an optional checksum. If you're interested in checksum mechanism, you may check [this](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md). In `web3j` library you can simply use `toChecksumAddress()` if neeed.
