### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Philipinho** [eirlis/web3j-example#2]
Hi @Eirlis, I'd love to contribute to this project. Will you accept my PRs?
I'm looking to add a progress bar while the wallet is generating and other enhancement.

Hope to hear from you soon. Thank you.

**Comment by eirlis** [comment]
Hi @Philipinho, it's really great that you've decided to add some features here, because this project currently just gathering dust on a shelf :) 
Absolutely love the idea of adding something new in there, so looking forward to see your PR's.

**Comment by Philipinho** [comment]
Thanks @Eirlis..
